LilianBittar/dotnet-blazor-ecommerce

src/Client/Shared/ProductList.razor.css

Added some css for styling

---

src/Client/Program.cs
src/Client/Shared/ProductList.razor
src/Server/Program.cs

* Implemented the call from the client so the data can be restore on the server and be retrieved on the client side.

Call the Web API from the client.

---

src/Server/Controllers/ProductController.cs

Overview:
* Improved controller.

Added swagger.

---

src/BlazorEcommerce.Shared/ServiceResponse.cs
src/Client/Shared/ProductList.razor
src/Server/Controllers/ProductController.cs

Implemented Service Response

---

src/Server/Controllers/ProductController.cs
src/Server/Services/ProductService/IProductService.cs
src/Server/Services/ProductService/ProductService.cs

#Overview 
* Implemented controller method.
* Implemented repository method.

implemented get product from server.

---

src/Client/Pages/ProductDetails.razor
src/Client/Pages/ProductDetails.razor.css
src/Client/Services/ProductService/IProductService.cs
src/Client/Services/ProductService/ProductService.cs
src/Client/Shared/ProductList.razor.css
src/Client/wwwroot/css/app.css

* Implemented get product by id on client
* Css fix by @LilianBittar

Get single product client

---

src/BlazorEcommerce.Shared/Category.cs
src/BlazorEcommerce.Shared/Product.cs

Add category model.

---

src/Client/Program.cs
src/Client/Services/CategoryService/CategoryService.cs
src/Client/Services/CategoryService/ICategoryService.cs
src/Client/_Imports.razor

Added category service to client

---

src/Server/Controllers/ProductController.cs
src/Server/Services/ProductService/IProductService.cs
src/Server/Services/ProductService/ProductService.cs

* Added getProductByid on server

added get product by category on serva

---

src/Client/Pages/Index.razor
src/Client/Services/ProductService/IProductService.cs
src/Client/Services/ProductService/ProductService.cs
src/Client/Shared/ProductList.razor

* Implemented get products by id on the client side.

Get product by category client

---

src/BlazorEcommerce.Shared/Product.cs
src/BlazorEcommerce.Shared/ProductType.cs
src/BlazorEcommerce.Shared/ProductVariant.cs
src/Client/Pages/ProductDetails.razor
src/Client/Shared/ProductList.razor

* Added product variant models

Added new models

---

src/Server/Data/DataContext.cs

* Seeded the data context with product types and variants

seeded data context

---

src/Server/Services/ProductService/ProductService.cs

Include product variants.

---

src/Client/Shared/ProductList.razor
src/Client/_Imports.razor

Display the price.

---

src/Client/Pages/ProductDetails.razor

* Implemented select box for the product.

implement a select box for the product variant.

---

src/Server/Controllers/ProductController.cs
src/Server/Services/ProductService/IProductService.cs
src/Server/Services/ProductService/ProductService.cs

* Implemented search product in service.
* Implemented search product in controller.

Implemented the search product.

---

src/Server/Controllers/ProductController.cs
src/Server/Services/ProductService/IProductService.cs
src/Server/Services/ProductService/ProductService.cs

* Implemented search suggestions.

Implemented search suggestions.

---

src/Client/Services/ProductService/IProductService.cs
src/Client/Services/ProductService/ProductService.cs
src/Client/Shared/ProductList.razor

* Implemented search methods on the client side.

Implemented search methods on the client.

---

src/Client/Pages/Index.razor
src/Client/Shared/MainLayout.razor
src/Client/Shared/Search.razor

#Overview
* Implemented search page.
* added search to main layout.

Search url

---

src/Client/App.razor
src/Client/Shared/HomeButton.razor
src/Client/Shared/HomeButton.razor.css
src/Client/Shared/ShopLayout.razor
src/Client/Shared/ShopLayout.razor.css
src/Client/Shared/ShopNavMenu.razor
src/Client/Shared/ShopNavMenu.razor.css

* added a home button.
* implemented shop layout.
* implemented shop nav bar.

Custom layout

---

src/Client/Pages/Register.razor

#Overview:
* Implemented registration page.

Implemented register page.

---

src/Server/Server.csproj
src/Server/Services/AuthService/AuthService.cs

Created json token web.

---

src/Client/Pages/Login.razor
src/Client/Services/AuthService/AuthService.cs
src/Client/Services/AuthService/IAuthService.cs
src/Client/Shared/UserButton.razor

Clippity cloppity bippity boop.
Flippity floppity slippity sloop.
Hippity hoppity dippity doop.
Zippity zoppty pippity poop.
Mippity moppity trippity troop.
Lippity loppity vippity voop.
Nippity noppity grippity groop.
Tippity toppity quippity quoop.
Drippity droppity jippity joop.
Blippity bloppity sippity soop.
Yippity yoppity whippity whoop.

Clippity Cloppity Bippity Boop
